import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import Image from "next/legacy/image";
import Footer from "@/components/footer";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kettle Valley Regional Plumbing & Gas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-main-bg flex flex-col min-h-screen`}
      >
        <header className="fixed flex mb-5 w-full bg-header-bg justify-between items-center z-10">
          <div className="fixed mt-20 pl-6 hidden md:flex">
            <Image src={"/kvr-logo.webp"} alt="logo" width={150} height={150} />
          </div>
          <div className="w-full relative">
            <div className="">
              <Navbar />
            </div>
          </div>
        </header>
        <main className="flex-1">{children}</main>
        <footer className="bg-header-bg text-text-white text-center py-4 z-10">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
