import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import Image from "next/legacy/image";
import Footer from "@/components/footer";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-main-bg flex flex-col min-h-screen`}
      >
        <header className="fixed top-0 flex w-full mb-5 bg-header-bg justify-between items-center z-10">
          <Link href="/" className="">
            <div className=" w-36 h-40 mr-2"></div>
          </Link>
          <div className="fixed" style={{ width: "150px", height: "150px" }}>
            <Image src={"/kvr-logo.webp"} alt="logo" width={150} height={150} />
          </div>
          <div className="w-full relative ml-24">
            <Navbar />
          </div>
        </header>
        <main className="mt-40 flex-1">{children}</main>
        <footer className="bg-header-bg text-text-white text-center py-4">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
